Add the transactions layer to the template layer.
It seems to be needed when cdi is used, or we get errors like:

[ERROR] org.wildfly.test.galleon.pack.template.subsystem.sanity.SubsystemSanityTestCase  Time elapsed: 5.684 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Cannot deploy sanity-test.war: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0412: Required services that are not installed:" => ["org.wildfly.transactions.global-default-local-provider"],"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.deployment.unit.\"sanity-test.war\".WeldTransactionServices is missing [org.wildfly.transactions.global-default-local-provider]"]}}}
	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:184)
	at org.jboss.as.arquillian.container.ArchiveDeployer.deployInternal(ArchiveDeployer.java:162)
	at org.jboss.as.arquillian.container.ArchiveDeployer.deploy(ArchiveDeployer.java:91)
	at org.jboss.as.arquillian.container.CommonDeployableContainer.deploy(CommonDeployableContainer.java:244)